### PR TITLE
Added Panzer General (lgeneral)

### PR DESCRIPTION
**Pull request by prahou**
I left the Tested string blank, as I haven't tested on -CURRENT.

### CODE REVIEW

**Comment by rfht** [comment]
thanks, can you change the space after every first word, like the README says `Game<TAB>Name`.

**Comment by stripedswan** [comment]
sorry about that, I thought it was only relevant to the line beginning with Game.

**Comment by prahou** [comment]
Nevermind, the issue was trying to write it in a browser.

**Comment by prahou** [comment]
redo-disregrad this

**Pull request closed without merging**
